from __future__ import annotations

ROLE_PREFIXES = [
    "koruyucu",
    "koruyucular",
    "renklendirici",
    "renklendiriciler",
    "renk verici",
    "asitlik düzenleyici",
    "asitlik düzenleyiciler",
    "asitlik duzenleyici",
    "asitlik duzenleyiciler",
    "emülgatör",
    "emülgatörler",
    "emulgator",
    "emulgatorler",
    "kabartıcı",
    "kabartıcılar",
    "kıvam arttırıcı",
    "kıvam arttırıcılar",
    "kivam arttirici",
    "kivam arttiricilar",
    "stabilizör",
    "stabilizörler",
    "stabilizer",
    "stabilizers",
    "aroma verici",
    "aroma vericiler",
    "antioksidan",
    "antioksidanlar",
]
